# Generated by Django 4.1.5 on 2023-01-17 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 23, 28, 17, 822263)),
        ),
    ]
